services:
  - type: web
    name: datifyy-backend
    runtime: node
    region: oregon
    buildCommand: cd services/nodejs-service && ./render-build.sh
    startCommand: cd services/nodejs-service && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: datifyy-db
          property: connectionString
    healthCheckPath: /health