import { ChildrenPreference, DatifyyUserPartnerPreferences, DrinkingPreference, GenderPreference, MaritalStatus, SmokingPreference } from "./types";

const emptyPartnerPreferences: DatifyyUserPartnerPreferences = {
  id: 0,
  genderPreference: GenderPreference.BOTH,
  minAge: null,
  maxAge: null,
  minHeight: null,
  maxHeight: null,
  religion: null,
  educationLevel: [],
  profession: [],
  minIncome: null,
  maxIncome: null,
  currency: null,
  locationPreference: null,
  smokingPreference: SmokingPreference.NO,
  drinkingPreference: DrinkingPreference.NO,
  maritalStatus: MaritalStatus.SINGLE,
  childrenPreference: ChildrenPreference.DOESNT_MATTER,
  religionPreference: null,
  ethnicityPreference: null,
  castePreference: null,
  partnerDescription: null,
  hobbies: [],
  interests: [],
  booksReading: [],
  music: [],
  movies: [],
  travel: [],
  sports: [],
  personalityTraits: [],
  relationshipGoals: null,
  lifestylePreference: null,
  locationPreferenceRadius: null,
  whatOtherPersonShouldKnow: null,
  activityLevel: null,
  petPreference: null,
  religionCompatibilityScore: null,
  incomeCompatibilityScore: null,
  educationCompatibilityScore: null,
  appearanceCompatibilityScore: null,
  personalityCompatibilityScore: null,
  valuesCompatibilityScore: null,
  matchingScore: null,
};

export default emptyPartnerPreferences;
