// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: common/enums.proto

/* eslint-disable */

/** User status */
export enum UserStatus {
  USER_STATUS_UNSPECIFIED = "USER_STATUS_UNSPECIFIED",
  USER_STATUS_ACTIVE = "USER_STATUS_ACTIVE",
  USER_STATUS_INACTIVE = "USER_STATUS_INACTIVE",
  USER_STATUS_SUSPENDED = "USER_STATUS_SUSPENDED",
  USER_STATUS_DELETED = "USER_STATUS_DELETED",
}
