// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: common/base.proto

/* eslint-disable */

/** Common response structure */
export interface ApiResponse<T> {
  success: boolean;
  message: string;
  /** Data will be handled as a generic type in TypeScript */
  data: T;
  error?: ErrorDetails | undefined;
  metadata?: ResponseMetadata | undefined;
}

/** Error details */
export interface ErrorDetails {
  code: string;
  message: string;
  /** Details will be handled as JSON string in TypeScript */
  details: string;
}

/** Response metadata */
export interface ResponseMetadata {
  requestId: string;
  timestamp: string;
  processingTime: number;
}

/** Pagination */
export interface PaginationRequest {
  page: number;
  limit: number;
  sortBy: string;
  /** "asc" or "desc" */
  sortOrder: string;
}

export interface PaginationResponse {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

/** Common timestamps */
export interface Timestamps {
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

/** Geographic coordinates */
export interface Coordinates {
  latitude: number;
  longitude: number;
}

/** Location information */
export interface LocationInfo {
  city: string;
  state: string;
  country: string;
  zipCode: string;
  coordinates?: Coordinates | undefined;
}
