// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: dating/curated_dates.proto

/* eslint-disable */
import type { PaginationResponse } from "../common/base";
import type { AdminPriority, CuratedDateStatus, DateMode, SortBy, SortOrder } from "./common";
import type { CuratedDate } from "./curation";

/** Response messages */
export interface CuratedDateResponse {
  success: boolean;
  data?: CuratedDate | undefined;
  message: string;
}

export interface CuratedDatesListResponse {
  success: boolean;
  dates: CuratedDate[];
  pagination?: PaginationResponse | undefined;
  message: string;
}

/** Get user dates request message with filters */
export interface GetUserDatesRequest {
  /** If not provided, use authenticated user */
  userId?: number | undefined;
  status: CuratedDateStatus[];
  /** YYYY-MM-DD */
  dateFrom?:
    | string
    | undefined;
  /** YYYY-MM-DD */
  dateTo?: string | undefined;
  mode?: DateMode | undefined;
  includeSeriesInfo?: boolean | undefined;
  includeFeedback?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: SortBy | undefined;
  sortOrder?: SortOrder | undefined;
}

/** Admin get dates request message with extensive filters */
export interface AdminGetDatesRequest {
  status: CuratedDateStatus[];
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  mode?: DateMode | undefined;
  city?: string | undefined;
  adminPriority?: AdminPriority | undefined;
  curatedBy?: number | undefined;
  hasUnreadFeedback?: boolean | undefined;
  requiresFollowUp?: boolean | undefined;
  seriesId?: string | undefined;
  user1Id?: number | undefined;
  user2Id?: number | undefined;
  minCompatibilityScore?: number | undefined;
  maxCompatibilityScore?: number | undefined;
  revenueImpactMin?: number | undefined;
  revenueImpactMax?: number | undefined;
  includeCancelledByAdmin?: boolean | undefined;
  includeWorkflowDetails?: boolean | undefined;
  includeTrustScores?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: SortOrder | undefined;
}
