// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: dating/curated_dates.proto

/* eslint-disable */
import type { DateType } from "../admin/revenue";
import type { Coordinates, PaginationRequest, PaginationResponse } from "../common/base";
import type { RelationshipStage } from "./curation";

/** Date status */
export enum CuratedDateStatus {
  CURATED_DATE_STATUS_UNSPECIFIED = "CURATED_DATE_STATUS_UNSPECIFIED",
  CURATED_DATE_STATUS_PENDING = "CURATED_DATE_STATUS_PENDING",
  CURATED_DATE_STATUS_CONFIRMED = "CURATED_DATE_STATUS_CONFIRMED",
  CURATED_DATE_STATUS_CANCELLED = "CURATED_DATE_STATUS_CANCELLED",
  CURATED_DATE_STATUS_COMPLETED = "CURATED_DATE_STATUS_COMPLETED",
  CURATED_DATE_STATUS_NO_SHOW = "CURATED_DATE_STATUS_NO_SHOW",
}

/** Cancellation category */
export enum CancellationCategory {
  CANCELLATION_CATEGORY_UNSPECIFIED = "CANCELLATION_CATEGORY_UNSPECIFIED",
  CANCELLATION_CATEGORY_PERSONAL_EMERGENCY = "CANCELLATION_CATEGORY_PERSONAL_EMERGENCY",
  CANCELLATION_CATEGORY_ILLNESS = "CANCELLATION_CATEGORY_ILLNESS",
  CANCELLATION_CATEGORY_WORK_CONFLICT = "CANCELLATION_CATEGORY_WORK_CONFLICT",
  CANCELLATION_CATEGORY_FAMILY_EMERGENCY = "CANCELLATION_CATEGORY_FAMILY_EMERGENCY",
  CANCELLATION_CATEGORY_TRANSPORTATION = "CANCELLATION_CATEGORY_TRANSPORTATION",
  CANCELLATION_CATEGORY_WEATHER = "CANCELLATION_CATEGORY_WEATHER",
  CANCELLATION_CATEGORY_NOT_INTERESTED = "CANCELLATION_CATEGORY_NOT_INTERESTED",
  CANCELLATION_CATEGORY_OTHER = "CANCELLATION_CATEGORY_OTHER",
}

/** Curation workflow stage */
export enum CurationWorkflowStage {
  CURATION_WORKFLOW_STAGE_UNSPECIFIED = "CURATION_WORKFLOW_STAGE_UNSPECIFIED",
  CURATION_WORKFLOW_STAGE_MATCHING = "CURATION_WORKFLOW_STAGE_MATCHING",
  CURATION_WORKFLOW_STAGE_VENUE_SELECTION = "CURATION_WORKFLOW_STAGE_VENUE_SELECTION",
  CURATION_WORKFLOW_STAGE_SCHEDULING = "CURATION_WORKFLOW_STAGE_SCHEDULING",
  CURATION_WORKFLOW_STAGE_CONFIRMATION = "CURATION_WORKFLOW_STAGE_CONFIRMATION",
  CURATION_WORKFLOW_STAGE_PAYMENT = "CURATION_WORKFLOW_STAGE_PAYMENT",
  CURATION_WORKFLOW_STAGE_COMPLETED = "CURATION_WORKFLOW_STAGE_COMPLETED",
}

export enum DateMode {
  DATE_MODE_UNSPECIFIED = "DATE_MODE_UNSPECIFIED",
  DATE_MODE_ONLINE = "DATE_MODE_ONLINE",
  DATE_MODE_OFFLINE = "DATE_MODE_OFFLINE",
}

/** Enum for sort by options */
export enum SortBy {
  SORT_BY_UNSPECIFIED = "SORT_BY_UNSPECIFIED",
  SORT_BY_DATE_TIME = "SORT_BY_DATE_TIME",
  SORT_BY_STATUS = "SORT_BY_STATUS",
  SORT_BY_CREATED_AT = "SORT_BY_CREATED_AT",
}

/** Enum for sort order */
export enum SortOrder {
  SORT_ORDER_UNSPECIFIED = "SORT_ORDER_UNSPECIFIED",
  SORT_ORDER_ASC = "SORT_ORDER_ASC",
  SORT_ORDER_DESC = "SORT_ORDER_DESC",
}

/** Enum for admin priority levels */
export enum AdminPriority {
  ADMIN_PRIORITY_UNSPECIFIED = "ADMIN_PRIORITY_UNSPECIFIED",
  ADMIN_PRIORITY_1 = "ADMIN_PRIORITY_1",
  ADMIN_PRIORITY_2 = "ADMIN_PRIORITY_2",
  ADMIN_PRIORITY_3 = "ADMIN_PRIORITY_3",
}

/** Curated date */
export interface CuratedDate {
  id: string;
  user1Id: number;
  user2Id: number;
  dateType: DateType;
  status: CuratedDateStatus;
  venueName: string;
  venueAddress: string;
  venueCoordinates?: Coordinates | undefined;
  scheduledDate: string;
  scheduledTime: string;
  estimatedCost: number;
  specialInstructions: string;
  workflowStage: CurationWorkflowStage;
  curatorAdminId: number;
  createdAt: string;
  updatedAt: string;
  confirmedAt: string;
  cancelledAt: string;
  cancellationCategory: CancellationCategory;
  cancellationReason: string;
  cancelledByUserId: number;
}

/** Date feedback */
export interface DateFeedback {
  id: string;
  curatedDateId: string;
  userId: number;
  overallRating: number;
  venueRating: number;
  partnerRating: number;
  curationRating: number;
  feedbackText: string;
  wouldRecommendVenue: boolean;
  wouldDatePartnerAgain: boolean;
  improvementSuggestions: string[];
  isAnonymous: boolean;
  submittedAt: string;
}

/** Date series */
export interface DateSeries {
  id: string;
  name: string;
  description: string;
  user1Id: number;
  user2Id: number;
  curatedDateIds: string[];
  totalDates: number;
  completedDates: number;
  relationshipStage: RelationshipStage;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Compatibility details */
export interface CompatibilityDetails {
  user1Id: number;
  user2Id: number;
  overallScore: number;
  factors: CompatibilityFactorType[];
  algorithmVersion: string;
  calculatedAt: string;
}

/** Compatibility factor */
export interface CompatibilityFactorType {
  factorName: string;
  score: number;
  weight: number;
  description: string;
}

/** Request messages */
export interface CreateCuratedDateRequest {
  user1Id: number;
  user2Id: number;
  dateType: DateType;
  preferredDate: string;
  preferredTime: string;
  preferredVenueType: string;
  specialRequests: string;
  budgetLimit: number;
}

export interface UpdateCuratedDateRequest {
  curatedDateId: string;
  status: CuratedDateStatus;
  venueName: string;
  venueAddress: string;
  venueCoordinates?: Coordinates | undefined;
  scheduledDate: string;
  scheduledTime: string;
  estimatedCost: number;
  specialInstructions: string;
  workflowStage: CurationWorkflowStage;
}

export interface ConfirmDateRequest {
  curatedDateId: string;
  userId: number;
  isConfirmed: boolean;
  notes: string;
}

export interface CancelDateRequest {
  curatedDateId: string;
  userId: number;
  cancellationCategory: CancellationCategory;
  cancellationReason: string;
  requestRefund: boolean;
}

export interface SubmitDateFeedbackRequest {
  curatedDateId: string;
  userId: number;
  overallRating: number;
  venueRating: number;
  partnerRating: number;
  curationRating: number;
  feedbackText: string;
  wouldRecommendVenue: boolean;
  wouldDatePartnerAgain: boolean;
  improvementSuggestions: string[];
  isAnonymous: boolean;
}

export interface GetCuratedDatesRequest {
  userId: number;
  statuses: CuratedDateStatus[];
  startDate: string;
  endDate: string;
  pagination?: PaginationRequest | undefined;
}

/** Response messages */
export interface CuratedDateResponse {
  success: boolean;
  data?: CuratedDate | undefined;
  message: string;
}

export interface CuratedDatesListResponse {
  success: boolean;
  dates: CuratedDate[];
  pagination?: PaginationResponse | undefined;
  message: string;
}

export interface DateFeedbackResponse {
  success: boolean;
  data?: DateFeedback | undefined;
  message: string;
}

export interface DateSeriesResponse {
  success: boolean;
  data?: DateSeries | undefined;
  message: string;
}

/** Get user dates request message with filters */
export interface GetUserDatesRequest {
  /** If not provided, use authenticated user */
  userId?: number | undefined;
  status: CuratedDateStatus[];
  /** YYYY-MM-DD */
  dateFrom?:
    | string
    | undefined;
  /** YYYY-MM-DD */
  dateTo?: string | undefined;
  mode?: DateMode | undefined;
  includeSeriesInfo?: boolean | undefined;
  includeFeedback?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: SortBy | undefined;
  sortOrder?: SortOrder | undefined;
}

/** Admin get dates request message with extensive filters */
export interface AdminGetDatesRequest {
  status: CuratedDateStatus[];
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  mode?: DateMode | undefined;
  city?: string | undefined;
  adminPriority?: AdminPriority | undefined;
  curatedBy?: number | undefined;
  hasUnreadFeedback?: boolean | undefined;
  requiresFollowUp?: boolean | undefined;
  seriesId?: string | undefined;
  user1Id?: number | undefined;
  user2Id?: number | undefined;
  minCompatibilityScore?: number | undefined;
  maxCompatibilityScore?: number | undefined;
  revenueImpactMin?: number | undefined;
  revenueImpactMax?: number | undefined;
  includeCancelledByAdmin?: boolean | undefined;
  includeWorkflowDetails?: boolean | undefined;
  includeTrustScores?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: SortOrder | undefined;
}
