// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.28.3
// source: admin/dashboard.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse } from "../common/base";

/** Dashboard metric types */
export enum DashboardMetricType {
  DASHBOARD_METRIC_TYPE_UNSPECIFIED = "DASHBOARD_METRIC_TYPE_UNSPECIFIED",
  DASHBOARD_METRIC_TYPE_USERS = "DASHBOARD_METRIC_TYPE_USERS",
  DASHBOARD_METRIC_TYPE_REVENUE = "DASHBOARD_METRIC_TYPE_REVENUE",
  DASHBOARD_METRIC_TYPE_DATES = "DASHBOARD_METRIC_TYPE_DATES",
  DASHBOARD_METRIC_TYPE_ENGAGEMENT = "DASHBOARD_METRIC_TYPE_ENGAGEMENT",
  DASHBOARD_METRIC_TYPE_CONVERSION = "DASHBOARD_METRIC_TYPE_CONVERSION",
}

/** Alert severity levels */
export enum AlertSeverityLevel {
  ALERT_SEVERITY_LEVEL_UNSPECIFIED = "ALERT_SEVERITY_LEVEL_UNSPECIFIED",
  ALERT_SEVERITY_LEVEL_INFO = "ALERT_SEVERITY_LEVEL_INFO",
  ALERT_SEVERITY_LEVEL_WARNING = "ALERT_SEVERITY_LEVEL_WARNING",
  ALERT_SEVERITY_LEVEL_ERROR = "ALERT_SEVERITY_LEVEL_ERROR",
  ALERT_SEVERITY_LEVEL_CRITICAL = "ALERT_SEVERITY_LEVEL_CRITICAL",
}

/** Dashboard overview data */
export interface DashboardOverview {
  userMetrics?: UserMetrics | undefined;
  revenueMetrics?: RevenueMetrics | undefined;
  dateMetrics?: DateMetrics | undefined;
  engagementMetrics?: EngagementMetrics | undefined;
  alerts: DashboardAlert[];
  trends: TrendData[];
  generatedAt: string;
}

/** User metrics */
export interface UserMetrics {
  totalUsers: number;
  activeUsers: number;
  newSignupsToday: number;
  newSignupsThisWeek: number;
  verifiedUsers: number;
  userGrowthRate: number;
  premiumUsers: number;
}

/** Revenue metrics */
export interface RevenueMetrics {
  totalRevenue: number;
  revenueToday: number;
  revenueThisWeek: number;
  revenueThisMonth: number;
  averageRevenuePerUser: number;
  revenueGrowthRate: number;
  successfulTransactions: number;
  failedTransactions: number;
}

/** Date metrics */
export interface DateMetrics {
  totalDatesCurated: number;
  datesToday: number;
  datesThisWeek: number;
  successfulDates: number;
  cancelledDates: number;
  dateSuccessRate: number;
  averageDateRating: number;
}

/** Engagement metrics */
export interface EngagementMetrics {
  dailyActiveUsers: number;
  weeklyActiveUsers: number;
  monthlyActiveUsers: number;
  averageSessionDuration: number;
  profileCompletionsToday: number;
  matchesMadeToday: number;
}

/** Dashboard alert */
export interface DashboardAlert {
  id: string;
  title: string;
  message: string;
  severity: AlertSeverityLevel;
  category: string;
  isRead: boolean;
  createdAt: string;
  actionUrl: string;
}

/** Trend data */
export interface TrendData {
  metricName: string;
  dataPoints: TrendPoint[];
  /** "day", "week", "month" */
  period: string;
  trendPercentage: number;
}

/** Trend point */
export interface TrendPoint {
  date: string;
  value: number;
}

/** Request messages */
export interface GetDashboardOverviewRequest {
  startDate: string;
  endDate: string;
  metricTypes: DashboardMetricType[];
  includeTrends: boolean;
  includeAlerts: boolean;
}

export interface GetDashboardAlertsRequest {
  severities: AlertSeverityLevel[];
  unreadOnly: boolean;
  pagination?: PaginationRequest | undefined;
}

export interface MarkAlertAsReadRequest {
  alertId: string;
}

/** Response messages */
export interface DashboardOverviewResponse {
  success: boolean;
  data?: DashboardOverview | undefined;
  message: string;
}

export interface DashboardAlertsResponse {
  success: boolean;
  alerts: DashboardAlert[];
  pagination?: PaginationResponse | undefined;
  message: string;
}
