// Auto-generated from proto/admin/enums.proto
// Generated at: 2025-07-15T14:41:46.185Z

export enum AdminPermissionLevel {
  UNSPECIFIED = 'UNSPECIFIED',
  VIEWER = 'VIEWER',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
}

export enum AdminPermission {
  UNSPECIFIED = 'UNSPECIFIED',
  VIEW_USERS = 'VIEW_USERS',
  EDIT_USERS = 'EDIT_USERS',
  DELETE_USERS = 'DELETE_USERS',
  VERIFY_USERS = 'VERIFY_USERS',
  BAN_USERS = 'BAN_USERS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  MODERATE_CONTENT = 'MODERATE_CONTENT',
  DELETE_CONTENT = 'DELETE_CONTENT',
  VIEW_EVENTS = 'VIEW_EVENTS',
  CREATE_EVENTS = 'CREATE_EVENTS',
  EDIT_EVENTS = 'EDIT_EVENTS',
  DELETE_EVENTS = 'DELETE_EVENTS',
  MANAGE_EVENT_REGISTRATIONS = 'MANAGE_EVENT_REGISTRATIONS',
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  PROCESS_REFUNDS = 'PROCESS_REFUNDS',
  VIEW_REVENUE_REPORTS = 'VIEW_REVENUE_REPORTS',
  MANAGE_PRICING = 'MANAGE_PRICING',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  EXPORT_DATA = 'EXPORT_DATA',
  VIEW_SYSTEM_METRICS = 'VIEW_SYSTEM_METRICS',
  MANAGE_ADMINS = 'MANAGE_ADMINS',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
  VIEW_LOGS = 'VIEW_LOGS',
  MANAGE_INTEGRATIONS = 'MANAGE_INTEGRATIONS',
}

export enum AdminSessionStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  INVALIDATED = 'INVALIDATED',
  LOCKED = 'LOCKED',
  PENDING_2FA = 'PENDING_2FA',
}

export enum AdminTwoFactorMethod {
  UNSPECIFIED = 'UNSPECIFIED',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  TOTP = 'TOTP',
  HARDWARE_KEY = 'HARDWARE_KEY',
}

export enum AdminAccountStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
  PENDING = 'PENDING',
  LOCKED = 'LOCKED',
}

export enum AdminActionType {
  UNSPECIFIED = 'UNSPECIFIED',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_BANNED = 'USER_BANNED',
  USER_VERIFIED = 'USER_VERIFIED',
  CONTENT_APPROVED = 'CONTENT_APPROVED',
  CONTENT_REJECTED = 'CONTENT_REJECTED',
  CONTENT_DELETED = 'CONTENT_DELETED',
  REPORT_RESOLVED = 'REPORT_RESOLVED',
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_DELETED = 'EVENT_DELETED',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  TRANSACTION_REVIEWED = 'TRANSACTION_REVIEWED',
  SYSTEM_CONFIG_CHANGED = 'SYSTEM_CONFIG_CHANGED',
  ADMIN_CREATED = 'ADMIN_CREATED',
  ADMIN_PERMISSIONS_CHANGED = 'ADMIN_PERMISSIONS_CHANGED',
}

export enum AdminRiskLevel {
  UNSPECIFIED = 'UNSPECIFIED',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AdminLoginAttemptResult {
  UNSPECIFIED = 'UNSPECIFIED',
  SUCCESS = 'SUCCESS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  REQUIRES_2FA = 'REQUIRES_2FA',
  INVALID_2FA = 'INVALID_2FA',
  RATE_LIMITED = 'RATE_LIMITED',
  IP_BLOCKED = 'IP_BLOCKED',
}

// Admin interface types
export interface AdminListFilters {
  permissionLevel?: AdminPermissionLevel;
  accountStatus?: AdminAccountStatus;
  email?: string;
  department?: string;
  createdAfter?: string;
  createdBefore?: string;
  lastLoginAfter?: string;
  lastLoginBefore?: string;
  search?: string;
}

export interface AdminTokenPayload {
  adminId: number;
  email: string;
  permissionLevel: AdminPermissionLevel;
  permissions: AdminPermission[];
  sessionId: string;
  iat: number;
  exp: number;
}

// Admin security constants
export const ADMIN_SECURITY_CONSTANTS = {
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 30,
  ACCOUNT_LOCK_DURATION: 30, // Same as LOCKOUT_DURATION_MINUTES
  TOKEN_EXPIRY_HOURS: 24,
  REFRESH_TOKEN_EXPIRY_DAYS: 30,
  SESSION_TIMEOUT_MINUTES: 60,
  SESSION_TIMEOUT_HOURS: 1, // 60 minutes = 1 hour
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_REQUIRE_UPPERCASE: true,
  PASSWORD_REQUIRE_LOWERCASE: true,
  PASSWORD_REQUIRE_NUMBERS: true,
  PASSWORD_REQUIRE_SYMBOLS: true,
  TWO_FACTOR_BACKUP_CODES_COUNT: 10,
  TWO_FACTOR_VALIDITY_MINUTES: 5,
  AUDIT_LOG_RETENTION_DAYS: 365,
} as const;

// Admin role permissions mapping
export const ADMIN_ROLE_PERMISSIONS = {
  [AdminPermissionLevel.VIEWER]: [
    AdminPermission.VIEW_USERS,
    AdminPermission.VIEW_ANALYTICS,
  ],
  [AdminPermissionLevel.MODERATOR]: [
    AdminPermission.VIEW_USERS,
    AdminPermission.MODERATE_CONTENT,
    AdminPermission.VIEW_ANALYTICS,
    AdminPermission.VIEW_EVENTS,
  ],
  [AdminPermissionLevel.ADMIN]: [
    AdminPermission.VIEW_USERS,
    AdminPermission.EDIT_USERS,
    AdminPermission.MODERATE_CONTENT,
    AdminPermission.VIEW_ANALYTICS,
    AdminPermission.VIEW_EVENTS,
    AdminPermission.CREATE_EVENTS,
    AdminPermission.EDIT_EVENTS,
    AdminPermission.VIEW_TRANSACTIONS,
  ],
  [AdminPermissionLevel.SUPER_ADMIN]: [
    AdminPermission.VIEW_USERS,
    AdminPermission.EDIT_USERS,
    AdminPermission.DELETE_USERS,
    AdminPermission.MODERATE_CONTENT,
    AdminPermission.VIEW_ANALYTICS,
    AdminPermission.VIEW_EVENTS,
    AdminPermission.CREATE_EVENTS,
    AdminPermission.EDIT_EVENTS,
    AdminPermission.DELETE_EVENTS,
    AdminPermission.VIEW_TRANSACTIONS,
    AdminPermission.PROCESS_REFUNDS,
    AdminPermission.MANAGE_ADMINS,
    AdminPermission.SYSTEM_CONFIG,
  ],
  [AdminPermissionLevel.OWNER]: Object.values(AdminPermission).filter(p => p !== AdminPermission.UNSPECIFIED),
} as const;

export enum RevenueTimePeriod {
  UNSPECIFIED = 'UNSPECIFIED',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum RevenueCategory {
  UNSPECIFIED = 'UNSPECIFIED',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  EVENT_FEES = 'EVENT_FEES',
  PREMIUM_FEATURES = 'PREMIUM_FEATURES',
  ADVERTISING = 'ADVERTISING',
  PARTNERSHIPS = 'PARTNERSHIPS',
  OTHER = 'OTHER',
}

export enum TransactionStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
  PROCESSING = 'PROCESSING',
}

export enum PaymentMethod {
  UNSPECIFIED = 'UNSPECIFIED',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  PAYPAL = 'PAYPAL',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
}

export enum TrendDirection {
  UNSPECIFIED = 'UNSPECIFIED',
  UP = 'UP',
  DOWN = 'DOWN',
  STABLE = 'STABLE',
}

export enum MatchAlgorithm {
  UNSPECIFIED = 'UNSPECIFIED',
  COLLABORATIVE_FILTERING = 'COLLABORATIVE_FILTERING',
  CONTENT_BASED = 'CONTENT_BASED',
  HYBRID = 'HYBRID',
  MACHINE_LEARNING = 'MACHINE_LEARNING',
  RULE_BASED = 'RULE_BASED',
}

export enum CompatibilityFactor {
  UNSPECIFIED = 'UNSPECIFIED',
  INTERESTS = 'INTERESTS',
  LOCATION = 'LOCATION',
  AGE = 'AGE',
  EDUCATION = 'EDUCATION',
  LIFESTYLE = 'LIFESTYLE',
  VALUES = 'VALUES',
  PERSONALITY = 'PERSONALITY',
  COMMUNICATION_STYLE = 'COMMUNICATION_STYLE',
}

export enum MatchConfidenceLevel {
  UNSPECIFIED = 'UNSPECIFIED',
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

export enum DateSuccessPrediction {
  UNSPECIFIED = 'UNSPECIFIED',
  VERY_UNLIKELY = 'VERY_UNLIKELY',
  UNLIKELY = 'UNLIKELY',
  NEUTRAL = 'NEUTRAL',
  LIKELY = 'LIKELY',
  VERY_LIKELY = 'VERY_LIKELY',
}

export enum MatchSuggestionStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  GENERATED = 'GENERATED',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
