version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    image: datifyy-backend:local
    container_name: datifyy-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_here
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=datifyy
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAILERSEND_API_KEY=your_mailersend_key_here
    depends_on:
      - db
      - redis
    networks:
      - datifyy-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: datifyy-db
    environment:
      - POSTGRES_DB=datifyy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datifyy-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: datifyy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - datifyy-network
    restart: unless-stopped

networks:
  datifyy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: